### PR TITLE
Bump ActiveRecord constraint < 6.2

### PR DESCRIPTION
**Pull request by joshRpowell**

### CODE REVIEW

**Review by sufleR — APPROVED** [review]

**Comment by sufleR** [comment]
@joshRpowell does it work for you with rails 6.1?

**Comment by joshRpowell** [comment]
Yes. No issues in production for > 1mo. 

Will circle back to update the test suite when I have a chance.

**Comment by ghost** [comment]
Any chance of 0.7.1 with this change included? (I'm blocked from upgrading from 0.6.0)

**Comment by sufleR** [comment]
@jjg-dressipi released 0.7.1

**Comment by ghost** [comment]
Thank you!

**Pull request merged**
